package launchpad

import (
	"context"
	"errors"
	"fmt"
	"os"
	"os/signal"
	"syscall"
	"time"

	"github.com/danilosciarra/launchpad/config"
	"github.com/danilosciarra/launchpad/dapr"
	"github.com/danilosciarra/launchpad/grpcserver"
	"github.com/danilosciarra/launchpad/httpserver"
	internallogging "github.com/danilosciarra/launchpad/internal/logging"
	"github.com/danilosciarra/launchpad/log"

	"github.com/gin-gonic/gin"
	"google.golang.org/grpc"
)

const defaultShutdownTimeout = 30 * time.Second

// App is a bootstrapped Launchpad application: an HTTP server, an optional
// gRPC server, and an optional Dapr sidecar connection, managed together.
// Build one with New.
type App struct {
	logger          log.Logger
	shutdownTimeout time.Duration

	http *httpserver.Server
	grpc *grpcserver.Server
	dapr *dapr.Client
}

// New builds an App from cfg. The HTTP server is always created; the gRPC
// server and Dapr client are created only when cfg.GRPC or cfg.Dapr are
// set, respectively.
func New(cfg *config.Config, opts ...Option) (*App, error) {
	if cfg == nil {
		return nil, errors.New("launchpad: config cannot be nil")
	}

	o := newOptions()
	for _, opt := range opts {
		opt(o)
	}

	logger := o.logger
	if logger == nil {
		logger = internallogging.New(cfg.Log)
	}

	shutdownTimeout := cfg.ShutdownTimeout
	if shutdownTimeout <= 0 {
		shutdownTimeout = defaultShutdownTimeout
	}

	app := &App{
		logger:          logger,
		shutdownTimeout: shutdownTimeout,
	}

	httpOpts := []httpserver.Option{httpserver.WithLogger(logger)}
	for group, mw := range o.middleware {
		httpOpts = append(httpOpts, httpserver.WithMiddleware(group, mw...))
	}
	if o.swagger != nil {
		o.swagger.Title = cfg.Name + " API"
		o.swagger.Version = cfg.Version
		o.swagger.Description = cfg.Description
		o.swagger.BasePath = "/"
		o.swagger.Schemes = []string{"http", "https"}
		httpOpts = append(httpOpts, httpserver.WithSwagger(o.swagger))
	}
	app.http = httpserver.New(cfg.HTTP, httpOpts...)

	if cfg.GRPC != nil {
		grpcOpts := []grpcserver.Option{grpcserver.WithLogger(logger)}
		for _, interceptor := range o.interceptors {
			grpcOpts = append(grpcOpts, grpcserver.WithUnaryInterceptor(interceptor))
		}
		app.grpc = grpcserver.New(*cfg.GRPC, grpcOpts...)
	}

	if cfg.Dapr != nil {
		client, err := dapr.New(*cfg.Dapr)
		if err != nil {
			return nil, fmt.Errorf("launchpad: %w", err)
		}
		app.dapr = client
	}

	return app, nil
}

// Engine returns the underlying *gin.Engine, for advanced use cases not
// covered by RegisterRoutes.
func (a *App) Engine() *gin.Engine {
	return a.http.Engine()
}

// HTTPServer returns the App's HTTP server.
func (a *App) HTTPServer() *httpserver.Server {
	return a.http
}

// GRPCServer returns the App's gRPC server, or nil if config.Config.GRPC
// was not set.
func (a *App) GRPCServer() *grpcserver.Server {
	return a.grpc
}

// Dapr returns the App's Dapr sidecar client, or nil if config.Config.Dapr
// was not set.
func (a *App) Dapr() *dapr.Client {
	return a.dapr
}

// Logger returns the logger the App was built with.
func (a *App) Logger() log.Logger {
	return a.logger
}

// RegisterRoutes registers HTTP routes under a path group. See
// httpserver.Server.RegisterRoutes.
func (a *App) RegisterRoutes(group string, routes ...httpserver.Route) error {
	return a.http.RegisterRoutes(group, routes...)
}

// RegisterGRPCService registers a gRPC service using the ServiceDesc
// generated by protoc. It returns an error if config.Config.GRPC was not
// set. See grpcserver.Server.RegisterService.
func (a *App) RegisterGRPCService(register func(*grpc.Server)) error {
	if a.grpc == nil {
		return errors.New("launchpad: gRPC server is not enabled (set config.Config.GRPC)")
	}
	a.grpc.RegisterService(register)
	return nil
}

// Run starts the HTTP server (and gRPC server, if enabled), then blocks
// until SIGINT or SIGTERM is received, at which point it gracefully shuts
// everything down before returning. For programmatic control over the
// application lifecycle (e.g. in tests), start the servers directly via
// HTTPServer/GRPCServer and call Shutdown yourself instead.
func (a *App) Run() error {
	if a.grpc != nil {
		if err := a.grpc.Start(); err != nil {
			return fmt.Errorf("launchpad: start gRPC server: %w", err)
		}
	}
	if err := a.http.Start(); err != nil {
		return fmt.Errorf("launchpad: start HTTP server: %w", err)
	}

	quit := make(chan os.Signal, 1)
	signal.Notify(quit, syscall.SIGINT, syscall.SIGTERM)
	<-quit

	a.logger.Infof("shutdown signal received, stopping all servers...")
	return a.Shutdown(context.Background())
}

// Shutdown gracefully stops the HTTP server, the gRPC server (if enabled)
// and the Dapr client (if enabled), bounded by the configured
// ShutdownTimeout.
func (a *App) Shutdown(ctx context.Context) error {
	shutdownCtx, cancel := context.WithTimeout(ctx, a.shutdownTimeout)
	defer cancel()

	var errs []error
	if a.grpc != nil {
		if err := a.grpc.Shutdown(shutdownCtx); err != nil {
			errs = append(errs, err)
		}
	}
	if err := a.http.Shutdown(shutdownCtx); err != nil {
		errs = append(errs, err)
	}
	if a.dapr != nil {
		if err := a.dapr.Close(); err != nil {
			errs = append(errs, err)
		}
	}

	a.logger.Infof("all servers stopped")
	return errors.Join(errs...)
}
